### ISSUE TITLE
README points to improper URL

### ISSUE THREAD

**Issue by Yuki-cpp** [MechMindRobotics/mecheye_ros_interface#12]
In the [How to use interface functions of Mech-Eye cameras](https://github.com/MechMindRobotics/mecheye_ros_interface#how-to-use-interface-functions-of-mech-eye-cameras) section, there is a link pointing to the following URL: https://www.mech-mind.com/download/CameraSDK.html

This link leads to a 404 page. The proper url should be: https://www.mech-mind.com/download/camera-sdk.html

**Comment by lipengfei0451** [comment]
Thanks!
