### ISSUE TITLE
Package should have separated service definition and camera executable

### ISSUE THREAD

**Issue by hungpham2511** [MechMindRobotics/mecheye_ros_interface#20]
Hi, the current repository contains a single ROS package that has both service definition and executable, this leads to catkin failing to build the package normally.

The solution is to break the package into 2 and introduce proper dependency.

I have a patch for that, would you be interested to accept the change?

**Comment by LiChen-MechMind** [comment]
> Hi, the current repository contains a single ROS package that has both service definition and executable, this leads to catkin failing to build the package normally.
> 
> The solution is to break the package into 2 and introduce proper dependency.
> 
> I have a patch for that, would you be interested to accept the change?
We have worked for it in the last few days, and we add sepcific code in CmakeLists.txt. Fow now, the clients only need to catkin_make once and it should work successfully.

**Comment by LiChen-MechMind** [comment]
@hungpham2511 
We have worked for it in the last few days, and we add specific code in CmakeLists.txt. Fow now, clients only need to catkin_make once and it should work successfully.

**Comment by hungpham2511** [comment]
Alright then. Closing the issue.
