### ISSUE TITLE
Q: insturctions to launch the ros mecheye?

### ISSUE THREAD

**Issue by sharronliu** [MechMindRobotics/mecheye_ros_interface#4]
Hello, could you give instructions how to launch the ros mecheye? I tried with `roslaunch mecheye_ros_interface xxx.launch` while it does not work.
In the `README`, I read the below sentence which gives no specific steps. Thanks.
`How to build and run sample project:`
`    Run with one Mech-Eye camera.`

**Comment by lianghongzhuo** [comment]
Did you build this project in ROS? What's your operating system version? Could you paste your error message here?

**Comment by sharronliu** [comment]
Here're my commands:
`source /opt/ros/melodic/setup.bash`
`catkin_make -DCMAKE_BUILD_TYPE=Release`
`source devel/setup.bash`
`roslaunch mecheye_ros_interface start_camera.launch`

Here's the log. It looks connecting to the default camera_ip. How can I get the actual IP from mecheye?
started roslaunch server http://192.168.0.3:41741/
SUMMARY
PARAMETERS
 * /mechmind_camera_start/camera_ip: 192.168.0.123
 * /mechmind_camera_start/save_file: False
 * /rosdistro: melodic
 * /rosversion: 1.14.3
NODES
  /
    mechmind_camera_start (mecheye_ros_interface/start)
auto-starting new master
process[master]: started with pid [22353]
ROS_MASTER_URI=http://192.168.0.3:11311
setting /run_id to f2da7a66-329c-11ea-9407-001fc69cb106
process[rosout-1]: started with pid [22364]
started core service [/rosout]
process[mechmind_camera_start-2]: started with pid [22367]
Connect to tcp://192.168.0.123:5577

**Comment by lianghongzhuo** [comment]
Yes, you should set up your camera's IP address [here](https://github.com/MechMindRobotics/mecheye_ros_interface/blob/master/launch/start_camera.launch#L4). 
You can log into your router's manage page to check the camera's IP address.

**Comment by lianghongzhuo** [comment]
@sharronliu Have you solved your problem? If you have any further questions, please let me know.

**Comment by sharronliu** [comment]
The camera is working on my side now. Thanks for your quick response. It looks great!
Just observed a few minor issues, if you can help to check:
1. the timestamp info is empty in the point cloud images and depth images.
2. the TF tree is not received

`$ rostopic echo /mechmind/depth_image/header
seq: 261
stamp: 
  secs: 0
  nsecs:         0
frame_id: "mechmind_camera"`

`$rostopic echo /tf_static 
WARNING: topic [/tf_static] does not appear to be published yet`

**Comment by lianghongzhuo** [comment]
1. I current did not add timestamp on point cloud and RGB topic. This should be added soon. Similar to what I add timestamp at  `"/mechmind/camera_info"` topic.
2. You should add a tf by yourself. Try this package: https://github.com/TAMS-Group/camera_positioner or this package: https://github.com/IFL-CAMP/easy_handeye
Both of them are methods to solve the tf from `world` to `camera`.

**Comment by lianghongzhuo** [comment]
camera info is now published after this pull request: https://github.com/MechMindRobotics/mecheye_ros_interface/pull/9
