### ISSUE TITLE
command to change resolution?

### ISSUE THREAD

**Issue by sharronliu** [MechMindRobotics/mecheye_ros_interface#8]
Hello, my colleagues use the model "Pro S" and wanted to change the output resolution of depth and color. Could you point the way to do that?

I found `Command::SetCameraConfig`, but didn't find the detailed parameters if resolution could be changed by sendRequest via such command.

Thanks,
Sharron

**Comment by MechMindRobotics** [comment]
The Pro S camera does not support variable resolution mode currently.
